---
- hosts: satellite-server
  connection: local
  become: True
  tasks:
    - name: import_role for Satellite_6_Ansible_Installation_Playbook
      import_role: 
        name: ../../Satellite_6_Ansible_Installation_Playbook

  vars_files:
    - /home/39575/git/Satellite_6_Ansible_Installation_Playbook/defaults/main.yml
